name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v3.0.0
      with:
        go-version: 1.18
        check-latest: true

    - name: Checkout code
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

    - name: Test
      run: make test
