
name: Create Release

on:
  push:
    branches:
    - main
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  GO_VERSION: 1.17.x

jobs:
  cli:
    # Only release CLI for tagged releases
    if: startsWith(github.event.ref, 'refs/tags/v')

    name: Release the CLI
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v2.2.0
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0
    - uses: sigstore/cosign-installer@581838fbedd492d2350a9ecd427a95d6de1e5d01 # v2.0.1
    - uses: goreleaser/goreleaser-action@68acf3b1adf004ac9c2f0a4259e85c5f66e99bef # v2.8.1
      with:
        version: v1.7.0
        install-only: true
    - name: Release
      run: make release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ko-build:
    name: Release apko image and Tekton Task
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    env:
      KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
      COSIGN_EXPERIMENTAL: "true"

    steps:
    - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v2.2.0
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: imjasonh/setup-ko@2c3450ca27f6e6f2b02e72a40f2163c281a1f675 # v0.4
      with:
        version: v0.11.1
    - uses: sigstore/cosign-installer@581838fbedd492d2350a9ecd427a95d6de1e5d01 # v2.0.1
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0
    - name: Login to registry
      run: |
        echo ${{ github.token }} | go run ./ login ghcr.io --username=${{ github.repository_owner }} --password-stdin

    - name: Generate Tekton Task
      run: |
        # If not a tagged release, override image tag to "canary"
        if [[ $GITHUB_REF != refs/tags/* ]]; then
          export GIT_VERSION=canary
        fi
        make ko-resolve
    - name: Attach to workflow
      uses: actions/upload-artifact@v3
      with:
        name: task.yaml
        path: task.yaml
    - name: Attach to release
      if: startsWith(github.ref, 'refs/tags/v')
      run: gh release upload ${{ github.ref }} task.yaml

    - name: Publish/Sign apko image
      run: |
        # If not a tagged release, override image tag to "canary"
        if [[ $GITHUB_REF != refs/tags/* ]]; then
          export GIT_VERSION=canary
        fi
        make sign-image

